### ISSUE TITLE
Missing Logo

### ISSUE THREAD

**Issue by Tereseus** [aschera/Capstone-Project-Colmar-Academy#1]
As you can see below your logo is missing at the top left both on the tab bar and in the actual page. You should look into applying a style type that is supported. You may need to contact the advisors to solve this issue as there can be quite a few issues that can cause this.

![image](https://user-images.githubusercontent.com/19315896/42137201-373e9674-7d36-11e8-8a7f-0a5cbf54bca7.png)

**Comment by aschera** [comment]
Hello,
The favicon was missing, but I added it. The logo shows when I open the page at
https://aschera.github.io/Capstone-Project-Colmar-Academy/
It also works when I open it locally.
So maybe an issue with the way you view the project.

**Comment by Tereseus** [comment]
I do see it now, it wasn't loading before though. Great job.
