### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Tereseus** [aschera/Capstone-Project-Colmar-Academy#2]
Great job on your HTML but you should use divs more as dividers/wrappers. You created the sections but need to apply identifiers to those sections. Other than that your HTML looks great, especially with your use of notes and on implementing video controls which is something not a lot of people do.

**Comment by aschera** [comment]
What do you mean when you say 'apply identifiers to those sections'. 
My sections have classes. for example:<section class="news">

**Comment by Tereseus** [comment]
Place IDs also look up the differences between class and id and when you
should use either.
